/* jshint esversion:6 */
import {aClass} from "./mapClasses/AClassClass.js";
import {edge} from "./mapClasses/EdgeClass.js";

export class extractedData{
    classesData() {
        return {
            101: {
                id: "101",
                imgUrl: "#",
                type: "class",
                name: "Fluids 101",
                name2: "enema watersports",
                prerequisites: "",
                days: "1 5",
                description: "You will learn to play with different liquids.",
                tier: "beginner",
                opt1: "Take one 250ml enema (any liquid) and hold it for 4minutes.",
                opt2: "Piss on yourself.",
                pass1: "Hold a 500ml enema for 8minutes.",
                pass2: "Piss on your face.",
                tags: "fluid"
            },
            201: {
                id: "201",
                imgUrl: "#",
                type: "class",
                name: "Fluid-play 201",
                name2: "enema watersports",
                prerequisites: "101",
                days: "1 5",
                description: "You will get comfortable with taking different fluids",
                tier: "intermediate",
                opt1: "Take one 500ml enema (any liquid) and hold it for 5minutes.",
                opt2: "Piss on your face.",
                pass1: "Hold a 500ml enema for 10minutes.",
                pass2: "Piss in your mouth.",
                tags: "fluid"
            },
            301: {
                id: "301",
                imgUrl: "#",
                type: "class",
                name: "Advanced fluids 301",
                name2: "enema watersports",
                prerequisites: "201",
                days: "1 5",
                description: "Liquids are your new fetish.",
                tier: "advanced",
                opt1: "Take one 500ml enema (any liquid) and hold it for 10minutes.",
                opt2: "Piss in your mouth.",
                pass1: "Hold a 750ml enema (any liquid) for 12minutes.",
                pass2: "Drink at least 50ml (1.7oz) of piss.",
                tags: "fluid"
            },
            401: {
                id: "401",
                imgUrl: "#",
                type: "class",
                name: "Fluidity 401",
                name2: "enema watersports",
                prerequisites: "301",
                days: "1 5",
                description: "You will learn to hold large amount of liquids.",
                tier: "master",
                opt1: "Take one 750ml enema (any liquid) and hold it for 10minutes.",
                opt2: "Drink at least 50ml (1.7oz) of piss.",
                pass1: "Hold a 1000ml enema (any liquid) for 15minutes.",
                pass2: "Drink at least 100ml (3.3oz) of piss.",
                tags: "fluid"
            },
            102: {
                id: "102",
                imgUrl: "#",
                type: "class",
                name: "Anal 102",
                name2: "anal",
                prerequisites: "",
                days: "1 3 5",
                description: "You will discover new pleasure zones.",
                tier: "beginner",
                opt1: "Fuck your ass for 5minutes with a dildo. (size S)",
                opt2: "Wear a buttplug for 30minutes (size S)",
                pass1: "Fuck your ass for 10minutes with a dildo (size S)",
                pass2: "Wear a buttplug for 60minutes (size S)",
                tags: "penetration"
            },
            302: {
                id: "302",
                imgUrl: "#",
                type: "class",
                name: "Advanced Anal 302",
                name2: "anal",
                prerequisites: "102",
                days: "1 3 5",
                description: "Learn how to take it in the ass - faster, deeper and bigger.",
                tier: "advanced",
                opt1: "Fuck your ass for 15minutes with a dildo. (size M).",
                opt2: "Fuck your ass for 10minutes with a dildo. (size L)",
                pass1: "Fuck your ass for 30minutes with a dildo. (size M).",
                pass2: "Fuck your ass for 20minutes with a dildo. (size L).",
                tags: "penetration"
            },
            402: {
                id: "402",
                imgUrl: "#",
                type: "class",
                name: "Deep Anal 402",
                name2: "anal",
                prerequisites: "302",
                days: "1 3 5",
                description: "You will learn to enjoy only anal.",
                tier: "master",
                opt1: "Fuck your ass for 30minutes with a dildo. (size M).",
                opt2: "Fuck your ass for 20minutes with a dildo. (size L).",
                pass1: "Fuck your ass for 60minutes with a dildo. (size L).",
                pass2: "Fuck your ass for 40minutes with a dildo. (size XL).",
                tags: "penetration"
            },
            103: {
                id: "103",
                imgUrl: "#",
                type: "class",
                name: "Chastity 103",
                name2: "chastity",
                prerequisites: "",
                days: "2 3 4",
                description: "You will be eased into chastity and the concept of not receiving pleasure.",
                tier: "beginner",
                opt1: "Wear a chastity device for 120minutes today.",
                opt2: "Wear a chastity device for 30minutes while watching porn.",
                pass1: "Wear a chastity device for 240minutes today.",
                pass2: "Wear a chastity device for 60minutes while watching porn.",
                tags: "chastity"
            },
            203: {
                id: "203",
                imgUrl: "#",
                type: "class",
                name: "Chastity 203",
                name2: "chastity",
                prerequisites: "103",
                days: "1 2 3 4",
                description: "You will learn to go for longer periods of time locked in chastity.",
                tier: "intermediate",
                opt1: "Wear a chastity device for 360minutes today.",
                opt2: "Wear a chastity device for 240minutes today. Watch at least 30minutes of porn while locked.",
                pass1: "Wear a chastity device for 480minutes.",
                pass2: "Sleep with a chastity device on tonight.",
                tags: "chastity"
            },
            303: {
                id: "303",
                imgUrl: "#",
                type: "class",
                name: "Longterm chastity 303",
                name2: "chastity",
                prerequisites: "203",
                days: "1 2 3 4",
                description: "You will forget what sexual pleasure feels like.",
                tier: "advanced",
                opt1: "Wear a chastity device for 1380minutes.",
                opt2: "Wear a chastity device for 720minutes. Watch at least 40minutes of porn while locked.",
                pass1: "Wear a chastity device for 1380minutes. Watch at least 60minutes of porn while locked.",
                pass2: "Lock yourself in chastity until you manage to achieve an anal orgasm.",
                tags: "chastity"
            },
            403: {
                id: "403",
                imgUrl: "#",
                type: "class",
                name: "Permanent Chastity 403",
                name2: "chastity",
                prerequisites: "303",
                days: "1 2 3 4 5",
                description: "Having your clit locked becomes your second nature.",
                tier: "master",
                opt1: "Wear a chastity device for 1440minutes.",
                opt2: "Wear a chastity device for 1440minutes.",
                pass1: "Spend 10080minutes in chastity.",
                pass2: "Lock yourself in chastity until you manage to achieve 2 anal orgasms.",
                tags: "chastity"
            },
            104: {
                id: "104",
                imgUrl: "#",
                type: "class",
                name: "Femininity 104",
                name2: "feminization",
                prerequisites: "",
                days: "2 3 4",
                description: 'You will start exploring your feminine sides. (See "Others" in "Info" for clothing info)',
                tier: "beginner",
                opt1: "Wear panties for 60minutes today.",
                opt2: "Wear a bra for 60minutes today.",
                pass1: "Wear cute underwear for 120minutes today.",
                pass2: "Listen to 30minutes of hypno while wearing a cute underwear.",
                tags: "feminization"
            },
            204: {
                id: "204",
                imgUrl: "#",
                type: "class",
                name: "Crossdressing 204",
                name2: "feminization",
                prerequisites: "104",
                days: "1 2 3 4",
                description: 'You will start learning to dress and think like a girl. (See "Others" in "Info" for clothing info)',
                tier: "intermediate",
                opt1: "Listen to 30minutes of hypno while wearing cute underwear and one other cute piece of clothing.",
                opt2: "Wear cute underwear and one other cute piece of clothing for 120minutes today.",
                pass1: "Wear cute underwear and two other cute pieces of clothing for 120minutes today. Listen to 30 minutes of hypno.",
                pass2: "Shave your crotch and armpits.",
                tags: "feminization"
            },
            304: {
                id: "304",
                imgUrl: "#",
                type: "class",
                name: "Feminization 304",
                name2: "feminization",
                prerequisites: "204",
                days: "1 2 3 4",
                description: "You will dress and think like a girl.",
                tier: "advanced",
                opt1: "Wear cute underwear and two other cute pieces of clothing for 120minutes. Listen to 30 minutes of hypno.",
                opt2: "Wear cute underwear and three other cute pieces of clothing for 180minutes.",
                pass1: "Wear cute underwear and three other cute pieces of clothing for 240minutes. Listen to 45 minutes of hypno.",
                pass2: "Shave your legs. Wear cute underwear, three other cute pieces of clothing, makeup and a wig (long hair) for 120minutes.",
                tags: "feminization"
            },
            404: {
                id: "404",
                imgUrl: "#",
                type: "class",
                name: "Gender Reassignment 404",
                name2: "feminization",
                prerequisites: "304",
                days: "1 2 3 4 5",
                description: "After this class nobody will be able to tell if you're a boy or not. Not even you.",
                tier: "master",
                opt1: "Wear cute underwear and cute clothes for 360minutes today. Listen to 40 minutes of hypno.",
                opt2: "Wear cute underwear, cute clothes, heels, makeup and a wig (long hair) for 240minutes today.",
                pass1: "Wear cute underwear and cute clothes for 1440minutes today. Listen to 60 minutes of hypno.",
                pass2: "Shave your whole body. Wear cute underwear, cute clothes, heels, makeup and a wig (long hair) for 720minutes today.",
                tags: "feminization"
            },
            105: {
                id: "105",
                imgUrl: "#",
                type: "class",
                name: "Oral 105",
                name2: "oral",
                prerequisites: "",
                days: "1 3 5",
                description: "You will learn how to pleasure a dick with your mouth.",
                tier: "beginner",
                opt1: "Give a 5minutes blowjob to a dildo (size S).",
                opt2: "Deepthroat (10cm/~4inch) a dildo (size S) 5times.",
                pass1: "Give a 10minutes blowjob to a dildo (size S).",
                pass2: "Deepthroat (10cm/~4inch) a dildo (size S) 10times.",
                tags: "penetration"
            },
            305: {
                id: "305",
                imgUrl: "#",
                type: "class",
                name: "Blowjobs 305",
                name2: "oral",
                prerequisites: "105",
                days: "1 3 5",
                description: "You will learn how to deepthroat.",
                tier: "advanced",
                opt1: "Give a 10minutes blowjob to a dildo (size M).",
                opt2: "Deepthroat (15cm/~6inch) a dildo (size M) 10times. Hold your last deepthroat for 3 seconds.",
                pass1: "Give a 15minutes blowjob to a dildo (size M).",
                pass2: "Deepthroat (15cm/~6inch) a dildo (size M) 20times. Hold at least two deepthroats for at least 6 seconds.",
                tags: "penetration"
            },
            405: {
                id: "405",
                imgUrl: "#",
                type: "class",
                name: "Deepthroat Practice 405",
                name2: "oral",
                prerequisites: "305",
                days: "1 3 5",
                description: "Your mouth will become as good as, if not better than your ass at pleasing a cock.",
                tier: "master",
                opt1: "Deepthroat (19cm/~7.5inch) a dildo (size L) 20times in one sitting.",
                opt2: "Deepthroat (19cm/~7.5inch) a dildo (size L) for 5 seconds straight - 5times.",
                pass1: "Deepthroat (19cm/~7.5inch) a dildo (size L) 30times in one sitting. ",
                pass2: "Deepthroat (19cm/~7.5inch) a dildo (size L) for 8 seconds straight - 10times.",
                tags: "penetration"
            },
            106: {
                id: "106",
                imgUrl: "#",
                type: "class",
                name: "Cum Play 106",
                name2: "cum-play",
                prerequisites: "",
                days: "1 3",
                description: "You will learn to play with your cum.",
                tier: "beginner",
                opt1: "Lick any precum that's left from your other activities.",
                opt2: "Give yourself a facial with cum (real or fake).",
                pass1: "Drink a cum load (real or fake).",
                pass2: "Use cum (real or fake) as lube for one of your oral or anal activities.",
                tags: "fluid"
            },
            306: {
                id: "306",
                imgUrl: "#",
                type: "class",
                name: "Cum Appreciation 306",
                name2: "cum-play",
                prerequisites: "106",
                days: "1 3",
                description: "You will learn to enjoy cum.",
                tier: "advanced",
                opt1: "Give yourself a facial with cum (real or fake).",
                opt2: "Use cum (real or fake) as lube for one of your oral or anal activities.",
                pass1: "Use cum (real or fake) as lube for one of your daily activities. Drink a cum load (real or fake) after you're done.",
                pass2: "Put cum (real or fake) inside a condom and then put it in your mouth for 5 minutes without tying it.",
                tags: "fluid"
            },
            406: {
                id: "406",
                imgUrl: "#",
                type: "class",
                name: "Cum Addiction 406",
                name2: "cum-play",
                prerequisites: "306",
                days: "1 3 5",
                description: "Cum will be your most delicious treat.",
                tier: "master",
                opt1: "Drink a cum load (real or fake).",
                opt2: "Use cum (real or fake) as lube for all of your daily activities.",
                pass1: "Drink a cum load (real or fake). Then use cum as lube for one of your daily tasks. Drink another load of cum when you're finished.",
                pass2: "Give yourself a cum facial for 20 minutes and drink another load of cum in the meantime.",
                tags: "fluid"
            },
            107: {
                id: "107",
                imgUrl: "#",
                type: "class",
                name: "Vaginal Insertions 107",
                name2: "female",
                prerequisites: "",
                days: "1 3 5",
                description: "You will learn to play with your pussy. (This is a female only class)",
                tier: "beginner",
                opt1: "Fuck your pusy for 5minutes with a dildo. (size S)",
                opt2: "Insert a dildo (size S) in your pussy for 10minutes.",
                pass1: "Fuck your pussy for 10minutes with a dildo (size S)",
                pass2: "Insert a dildo (size M) in your pussy for 15minutes.",
                tags: "female"
            },
            207: {
                id: "207",
                imgUrl: "#",
                type: "class",
                name: "Pussy Stretching 207",
                name2: "female",
                prerequisites: "107",
                days: "1 3 5",
                description: "You will stretch your dirty cunt. (This is a female only class)",
                tier: "intermediate",
                opt1: "Fuck your pussy for 10minutes with a dildo (size S)",
                opt2: "Insert a dildo (size M) in your pussy for 15minutes.",
                pass1: "Fuck your pussy for 10minutes with a dildo (size M)",
                pass2: "Insert a dildo (size L) in your pussy for 15minutes.",
                tags: "female"
            },
            307: {
                id: "307",
                imgUrl: "#",
                type: "class",
                name: "Female Training 307",
                name2: "female",
                prerequisites: "207 215",
                days: "2 4",
                description: "You will put your pussy to work. (This is a female only class)",
                tier: "advanced",
                opt1: "Fuck your pussy for 15minutes with a dildo. (size M).",
                opt2: "Fuck your pussy for 10minutes with a dildo. (size L)",
                pass1: "Fuck your pussy for 30minutes with a dildo. (size M).",
                pass2: "Fuck your pussy for 20minutes with a dildo. (size L).",
                tags: "female"
            },
            407: {
                id: "407",
                imgUrl: "#",
                type: "class",
                name: "Feminism 407",
                name2: "female",
                prerequisites: "307",
                days: "2 4",
                description: "You will experience sexual empowerment and liberation. (This is a female only class)",
                tier: "master",
                opt1: "Fuck your ass for 30minutes with a dildo. (size M).",
                opt2: "Fuck your ass for 20minutes with a dildo. (size L).",
                pass1: "Fuck your ass for 60minutes with a dildo. (size L).",
                pass2: "Fuck your ass for 40minutes with a dildo. (size XL).",
                tags: "female"
            },
            118: {
                id: "118",
                imgUrl: "#",
                type: "class",
                name: "Exotic Materials 108",
                name2: "fetish",
                prerequisites: "",
                days: "2 3 4",
                description: 'You will learn to work with exotic materials such as latex, leather, PVC and vinyl. (See "Others" in "Info" for clothing info)',
                tier: "beginner",
                opt1: "Wear a fetish piece of clothing for 120minutes today.",
                opt2: "Wear two fetish pieces of clothing for 60minutes.",
                pass1: "Wear a fetish piece of clothing for 180minutes today.",
                pass2: "Wear two fetish pieces of clothing for 120minutes today.",
                tags: "fetish"
            },
            218: {
                id: "218",
                imgUrl: "#",
                type: "class",
                name: "Fetish Materials 208",
                name2: "fetish",
                prerequisites: "118",
                days: "2 3 4",
                description: "You will dress in fetish materials such as latex, leather, PVC and vinyl.",
                tier: "intermediate",
                opt1: "Wear two fetish pieces of clothing for 120minutes today.",
                opt2: "Wear three fetish pieces of clothing for 60minutes today.",
                pass1: "Wear three fetish pieces of clothing  for 120minutes today.",
                pass2: "Wear four fetish pieces of clothing for 60minutes today.",
                tags: "fetish"
            },
            318: {
                id: "318",
                imgUrl: "#",
                type: "class",
                name: "Fetish Clothing 308",
                name2: "fetish",
                prerequisites: "218",
                days: "1 3 4",
                description: "You will start exploring the world of fetish clothing. (Corsets also count)",
                tier: "advanced",
                opt1: "Wear four fetish pieces of clothing for 120minutes today.",
                opt2: "Wear a catsuit (bodysuit) for 120minutes today.",
                pass1: "Wear four fetish pieces of clothing for 240minutes today.",
                pass2: "Wear a catsuit (bodysuit) for 180minutes today.",
                tags: "fetish"
            },
            418: {
                id: "418",
                imgUrl: "#",
                type: "class",
                name: "Fetishism 408",
                name2: "fetish",
                prerequisites: "318",
                days: "2 3 4",
                description: "You will become a true fetishist.",
                tier: "master",
                opt1: "Wear four fetish pieces of clothing or a catsuit for 180minutes today.",
                opt2: "Wear a catsuit (bodysuit) and a hood/mask for 120minutes today.",
                pass1: "Wear four fetish pieces of clothing or a catsuit for 240minutes today.",
                pass2: "Wear a catsuit (bodysuit) and a hood/mask for 180minutes today.",
                tags: "fetish"
            },
            209: {
                id: "209",
                imgUrl: "#",
                type: "class",
                name: "Orgasm Training 209",
                name2: "orgasm",
                prerequisites: "",
                days: "6 0",
                description: "You will learn to orgasm multiple times. (This is a weekend only class)",
                tier: "intermediate",
                opt1: "Cum once today but continue all stimulation for 15 seconds after orgasm.",
                opt2: "Cum 2 times today.",
                pass1: "Cum once today but continue all stimulation for 30 seconds after orgasm.",
                pass2: "Cum 3 times today.",
                tags: "orgasm"
            },
            309: {
                id: "309",
                imgUrl: "#",
                type: "class",
                name: "Forced Orgasms 309",
                name2: "orgasm",
                prerequisites: "209",
                days: "6 0",
                description: "You'll be forced to orgasm multiple times. (This is a weekend only class)",
                tier: "advanced",
                opt1: "Cum once today but continue all stimulation for 30 seconds after orgasm.",
                opt2: "Cum 2 times in 30minutes.",
                pass1: "Cum once today but continue all stimulation for 60 seconds after orgasm.",
                pass2: "Cum 3 times in 45minutes.",
                tags: "orgasm"
            },
            409: {
                id: "409",
                imgUrl: "#",
                type: "class",
                name: "Orgasm Torture 409",
                name2: "orgasm",
                prerequisites: "309",
                days: "6 0",
                description: "You'll be forced to cum against your will. (This is a weekend only class)",
                tier: "master",
                opt1: "Cum once today but continue all stimulation for 60 seconds after orgasm.",
                opt2: "Cum 3 times in 45minutes.",
                pass1: "Cum once today but continue all stimulation for 2 minutes after orgasm.",
                pass2: "Cum 4 times in 60minutes.",
                tags: "orgasm"
            },
            213: {
                id: "213",
                imgUrl: "#",
                type: "class",
                name: "Edging 110",
                name2: "orgasm-denial",
                prerequisites: "",
                days: "1 3 4",
                description: "You will learn to hold back your orgasms. (If you are locked in chastity, unlock yourself to complete your task. Don't forget to re-lock yourself after)",
                tier: "beginner",
                opt1: "Masturbate for 10minutes.",
                opt2: "Edge 2times.",
                pass1: "Masturbate for 20minutes.",
                pass2: "Edge 4times.",
                tags: "orgasm"
            },
            313: {
                id: "313",
                imgUrl: "#",
                type: "class",
                name: "Tease and Denial 310",
                name2: "orgasm-denial",
                prerequisites: "213",
                days: "1 2 3 4",
                description: "You will learn to stay on the edge and deny your orgasms. (If you are locked in chastity, unlock yourself to complete your class workload. Don't forget to re-lock yourself after)",
                tier: "advanced",
                opt1: "Masturbate for 20minutes and edge 2times. No cumming allowed today.",
                opt2: "Edge 3times. No cumming allowed today.",
                pass1: "Masturbate for 30minutes and edge 4times. No cumming allowed today.",
                pass2: "Edge 5times. No cumming allowed today.",
                tags: "orgasm"
            },
            413: {
                id: "413",
                imgUrl: "#",
                type: "class",
                name: "Orgasm Denial 410",
                name2: "orgasm-denial",
                prerequisites: "313",
                days: "1 2 3 4",
                description: "Sexual frustration is your new natural state. (If you are locked in chastity, unlock yourself to complete your class workload. Don't forget to re-lock yourself after)",
                tier: "master",
                opt1: "Masturbate for 30minutes and edge 3times. No cumming allowed today.",
                opt2: "Edge 4times. No cumming allowed today.",
                pass1: "Masturbate for 45minutes and edge 6times. No cumming allowed today.",
                pass2: "Edge 8times. No cumming allowed today.",
                tags: "orgasm"
            },
            211: {
                id: "211",
                imgUrl: "#",
                type: "class",
                name: "Prostate Play 211",
                name2: "anal",
                prerequisites: "102",
                days: "1 4",
                description: "You will learn how to feel pleasure from your prostate.",
                tier: "intermediate",
                opt1: "Fuck yourself for 10minutes with a dildo (size M). Aim for your prostate.",
                opt2: "Fuck yourself for with a dildo (size M) until you start leaking.  Aim for your prostate.",
                pass1: "Fuck yourself 20minutes with a dildo (size M). Aim for your prostate.",
                pass2: "Fuck yourself for with a dildo (size M) until you start leaking. Then continue for another 10 minutes. Aim for your prostate.",
                tags: "anal"
            },
            311: {
                id: "311",
                imgUrl: "#",
                type: "class",
                name: "Prostate Milking 311",
                name2: "anal",
                prerequisites: "211",
                days: "1 4",
                description: "You will learn how to milk your prostate.",
                tier: "advanced",
                opt1: "Milk your prostate with a vibrator or a prostate massager for 30minutes.",
                opt2: "Milk your prostate with a vibrator or a prostate massager until you start leaking. Then continue for 10 minutes.",
                pass1: "Milk your prostate with a vibrator or a prostate massager for 60minutes.",
                pass2: "Milk your prostate with a vibrator or a prostate massager until you cum.",
                tags: "penetration"
            },
            212: {
                id: "212",
                imgUrl: "#",
                type: "class",
                name: "Buttplug Training 212",
                name2: "anal",
                prerequisites: "102",
                days: "1 3",
                description: "You will expand your anal horizons.",
                tier: "intermediate",
                opt1: "Wear a buttplug (size S) for 90minutes today.",
                opt2: "Wear a buttplug (size M) for 60minutes today.",
                pass1: "Wear a buttplug (size S) for 180minutes today.",
                pass2: "Wear a buttplug (size M) for 120minutes today.",
                tags: "penetration"
            },
            312: {
                id: "312",
                imgUrl: "#",
                type: "class",
                name: "Buttplug Stretching 312",
                name2: "anal",
                prerequisites: "212",
                days: "1 3",
                description: "You will expand your anal horizons with a larger set of plugs.",
                tier: "advanced",
                opt1: "Wear a buttplug (size M) for 180minutes.",
                opt2: "Wear a buttplug (size L) for 120minutes.",
                pass1: "Wear a buttplug (size L) for 240minutes.",
                pass2: "Wear a buttplug (size XL) for 180minutes.",
                tags: "penetration"
            },
            214: {
                id: "214",
                imgUrl: "#",
                type: "class",
                name: "Bondage 214",
                name2: "slave",
                prerequisites: "",
                days: "3 4",
                description: "You will learn the basics of self-bondage.",
                tier: "intermediate",
                opt1: "Cuff your legs together for 20minutes.",
                opt2: "Cuff your hands together for 20minutes.",
                pass1: "Cuff both your legs and hands for 30minutes.",
                pass2: "Tie yourself in a hogtie/frog-tie/lotus-tie/mummy-tie for 15minutes.",
                tags: "slave"
            },
            314: {
                id: "314",
                imgUrl: "#",
                type: "class",
                name: "Heavy Bondage 314",
                name2: "slave",
                prerequisites: "214",
                days: "2 4",
                description: "You will learn to endure pain and punishment. ",
                tier: "advanced",
                opt1: "Attach clothespins to your nipples for 5minutes and spank your ass 20times.",
                opt2: "Tie yourself in a hogtie/frog-tie/lotus-tie/mummy-tie tie for 15minutes.",
                pass1: "Attach clothespins to your nipples for 10minutes and spank your ass 40times.",
                pass2: "Tie yourself in a hogtie/frog-tie/lotus-tie/mummy-tie for 20minutes while blindfolded and gagged.",
                tags: "slave"
            },
            414: {
                id: "414",
                imgUrl: "#",
                type: "class",
                name: "Masochism 414",
                name2: "slave",
                prerequisites: "314",
                days: "2 3",
                description: "",
                tier: "master",
                opt1: "Attach clothespins to your nipples for 10minutes and spank your ass 30times. Then slap your balls/pussy 5times.",
                opt2: "Tie yourself in a hogtie/frog-tie/lotus-tie/mummy-tie for 20minutes while blindfolded and gagged.",
                pass1: "Attach clothespins to your nipples and tie yourself in a hogtie/frog-tie/lotus-tie/mummy-tie for 15minutes while blindfolded and gagged.",
                pass2: "Gag yourself and attach clothespins to your nipples. Spank yourself hard at least 30times on each butt cheek with an object. Then slap your balls/pussy 10times.",
                tags: "slave"
            },
            215: {
                id: "215",
                imgUrl: "#",
                type: "class",
                name: "Sex Training 215",
                name2: "oral anal",
                prerequisites: "102 105",
                days: "2 4",
                description: "Time to put your oral and anal skills to the test.",
                tier: "intermediate",
                opt1: "Spitroast yourself for 8minutes with two dildos (sizes S and M)",
                opt2: "Fuck yourself in the ass with a dildo (size M) for 5minutes and then give it a 5minutes blowjob.",
                pass1: "Spitroast yourself for 15minutes with two dildos (sizes S and M)",
                pass2: "Fuck yourself in the ass with a dildo (size M) for 10minutes and then give it a 5minutes blowjob.",
                tags: "penetration"
            },
            415: {
                id: "415",
                imgUrl: "#",
                type: "class",
                name: "Double Penetration 415",
                name2: "oral anal",
                prerequisites: "215 302 305",
                days: "2 4",
                description: "You will be trained to take multiple toys at once.",
                tier: "master",
                opt1: "Spitroast yourself for 15minutes with two dildos (sizes M and L)",
                opt2: "Fuck yourself in the ass with a dildo (size L) for 10minutes. Leave it in and then give another one (size M) a 5minutes blowjob with at least 10 deepthroats.",
                pass1: "Spitroast yourself for 25minutes with two dildos (sizes M and L)",
                pass2: "Fuck yourself in the ass with a dildo (size L) for 15minutes. Leave it in and then give another one (size M) a 10minutes blowjob with at least 30 deepthroats.",
                tags: "anal oral"
            },
            216: {
                id: "216",
                imgUrl: "#",
                type: "class",
                name: "Exposure 216",
                name2: "exhibitionism",
                prerequisites: "",
                days: "1 4",
                description: "You will overcome your shyness.",
                tier: "intermediate",
                opt1: "Perform one of your daily tasks with the window open.",
                opt2: "Tell the public how your daily tasks go. This can be in chat or online (4chan/reddit/)",
                pass1: "Go outside while wearing an item from your other classes (chastity, buttplug, dildo etc). The item can be hidden under your clothes.",
                pass2: "Take photos while performing your daily tasks and share them to the public (in chat or online)",
                tags: "exhibitionism"
            },
            316: {
                id: "316",
                imgUrl: "#",
                type: "class",
                name: "Publicity 316",
                name2: "exhibitionism",
                prerequisites: "216",
                days: "1 4",
                description: "Time to come out of the closet.",
                tier: "advanced",
                opt1: "Go outside while wearing an item from your other classes (chastity, buttplug, dildo etc). The item can be hidden under your clothes.",
                opt2: "Take photos while performing your daily tasks and share them to the public (in chat or online).",
                pass1: "Go outside and take a photo that shows you wearing an item from another class. The photo can be taken at a semi-public place (bathroom, changing room etc). Share the photo in chat or online.",
                pass2: "Record a 5 minute video of yourself while performing another task from the university and share it publicly.",
                tags: "exhibitionism"
            },
            416: {
                id: "416",
                imgUrl: "#",
                type: "class",
                name: "Exhibitionism 416",
                name2: "exhibitionism",
                prerequisites: "316",
                days: "1 4",
                description: "You completely overcome your instinct towards shame.",
                tier: "master",
                opt1: "Go outside and take a photo that shows you wearing an item from another class. The photo must be taken at a semi-public place (bathroom, changing room etc). Share the photo in chat or online.",
                opt2: "Record a 5 minute video of yourself performing another university task and share it in chat or online.",
                pass1: "Go outside and take a photo that shows you wearing an item from another class. The photo must be taken at a public place (park, street etc.). Share the photo in chat or online.",
                pass2: "Live-stream your university tasks and share it publicly. (Minimum 10 minutes)",
                tags: "public"
            },
            217: {
                id: "217",
                imgUrl: "#",
                type: "class",
                name: "Pet play 117",
                name2: "pet-play",
                prerequisites: "",
                days: "1 4 5",
                description: "You will start exploring the pet play lifestyle.",
                tier: "beginner",
                opt1: "Wear animal ears and a collar for 60minutes today.",
                opt2: "Wear animal ears, a collar and a tail for 30minutes today.",
                pass1: "Wear animal ears, a collar and a tail for 60minutes today.",
                pass2: "Wear animal ears, a collar and a tail for 30minutes today. Walk on all fours.",
                tags: "pet"
            },
            317: {
                id: "317",
                imgUrl: "#",
                type: "class",
                name: "Pet Training 317",
                name2: "pet-play",
                prerequisites: "217",
                days: "2 4",
                description: "You will learn to behave like a pet.",
                tier: "advanced",
                opt1: "Wear animal ears, a collar and a tail for 60minutes today.",
                opt2: "Wear animal ears, a collar and a tail for 30minutes today. Walk on all fours.",
                pass1: "Wear animal ears, a collar and a tail for 120minutes today.",
                pass2: "Wear animal ears, a collar and a tail for 60minutes today. Walk on all fours. Eat and drink from a bowl on the floor.",
                tags: "pet"
            },
            417: {
                id: "417",
                imgUrl: "#",
                type: "class",
                name: "Animal Training 417",
                name2: "pet-play",
                prerequisites: "317",
                days: "2 4",
                description: "You will become a human pet.",
                tier: "master",
                opt1: "Wear animal ears, a collar and a tail for 60minutes today. Walk on all fours. Eat and drink from a bowl on the floor.",
                opt2: "Wear animal ears, a collar and a buttplug tail for 30minutes today. Tie yourself in a bitchsuit position.",
                pass1: "Wear animal ears, a collar and a tail for 120minutes today. Walk on all fours. Eat and drink from a bowl on the floor.",
                pass2: "Wear animal ears, a collar and a buttplug tail for 60minutes today. Tie yourself in a bitchsuit position.",
                tags: "public"
            },
            220: {
                id: "220",
                imgUrl: "#",
                type: "class",
                name: "Obedience 220",
                name2: "slave",
                prerequisites: "",
                days: "2 3",
                description: "You will learn to follow command.",
                tier: "intermediate",
                opt1: "Roll a random Light Punishment 1times.",
                opt2: "Request a slave task in chat or online 1times.",
                pass1: "Roll a random Light Punishment 2times.",
                pass2: "Request a slave task in chat or online 2times.",
                tags: "slave"
            },
            320: {
                id: "320",
                imgUrl: "#",
                type: "class",
                name: "Submission 320",
                name2: "slave",
                prerequisites: "220",
                days: "2 3",
                description: "You will learn to obey your master's commands.",
                tier: "advanced",
                opt1: "Roll a random Light Punishment 2times.",
                opt2: "Request a slave task in chat or online 2times.",
                pass1: "Roll a random Heavy Punishment 1times.",
                pass2: "Request a hard slave task in chat or online 3times.",
                tags: "slave"
            },
            420: {
                id: "420",
                imgUrl: "#",
                type: "class",
                name: "Slavery 420",
                name2: "slave",
                prerequisites: "320",
                days: "2 3 4",
                description: "You will learn to obey your master's commands.",
                tier: "master",
                opt1: "Roll a random Heavy Punishment and a random Light Punishment 1times.",
                opt2: "Request a hard slave task in chat or online 3times.",
                pass1: "Roll a random Heavy Punishment and a random Light Punishment 2times.",
                pass2: "Request a hard slave task in chat or online 4times.",
                tags: "slave"
            }
        }
    }

    majorsData() {
        return {
            1: {
                id: "1",
                imgUrl: "#",
                type: "major",
                name: "Anal Technologies",
                name2: "anal",
                prerequisites: "311 312 402",
                description: "You will devote your life to an anal only lifestyle.",
                tier: "major",
                opt1: "none",
                opt2: "none",
                pass1: "Wear a buttplug (size XL) for 4 hours. Then fuck your ass with a dildo (size XL) for 40 minutes. Keep going even if you cum.",
                pass2: "Wear a buttplug (size L) for 1440minutes.",
                pass3: "Cum from anal 2 times in 1440minutes. Use a dildo (size XL).",
                tags: "anal"
            },
            2: {
                id: "2",
                imgUrl: "#",
                type: "major",
                name: "Gender Studies",
                name2: "chastity, feminization",
                prerequisites: "403 404",
                description: "You will take control of your gender and become a female in all ways except one.",
                tier: "major",
                opt1: "none",
                opt2: "none",
                pass1: "Spend 20160minutes in chastity while wearing cute underwear. You can cum only from anal.",
                pass2: "Spend 10080minutes in chastity while wearing cute underwear. Wear at least one cute piece of clothing (skirt/dress/pantyhose/stockings/heels etc) during the day for at least 4 hours (can be hidden under clothes). You can cum only from anal. Make sure your crotch and armpits are shaved.",
                pass3: "Spend 2880minutes in chastity while dressed like a girl - underwear, makeup, nails, wig (long hair) and cute clothes. Cum from anal at least once. Make sure your whole body is shaved smooth.",
                tags: "feminization chastity"
            },
            3: {
                id: "3",
                imgUrl: "#",
                type: "major",
                name: "Sex Psychology",
                name2: "chastity, orgasm denial",
                prerequisites: "403 413",
                description: "You will study the effects of sexual frustration on the human psyche.",
                tier: "major",
                opt1: "none",
                opt2: "none",
                pass1: "For 20160minutes - edge 1 time every day. If you cum, add 4 days to your time (press Punish).",
                pass2: "For 14400minutes - edge 2 times every day. Keep yourself in chastity for the rest of the time. If you cum, add 3 days to your time (press Punish).",
                pass3: "For 10080minutes - edge 3 times a day. Keep yourself locked in chastity for the rest of the time. If you cum, add 2 days to your time (press Punish).",
                tags: "chastity masturbation"
            },
            5: {
                id: "5",
                imgUrl: "#",
                type: "major",
                name: "Fluid Mechanics",
                name2: "enemas, watersports",
                prerequisites: "401",
                description: "You will master various fluids.",
                tier: "major",
                opt1: "none",
                opt2: "none",
                pass1: "Hold a 1500ml enema (any liquid) for 15minutes.",
                pass2: "Take a 1000ml enema for 10minutes and drink at least 200ml (10oz) of piss in the meantime.",
                pass3: "Fill an enema bag (container) with 600ml of piss and run the tube down to your mouth. Slowly drink it all up. (If you tie yourself and use a gag, you can go with just 400ml of piss)",
                tags: "fluid"
            },
            6: {
                id: "6",
                imgUrl: "#",
                type: "major",
                name: "Public Relations",
                name2: "exhibitionism, slave",
                prerequisites: "416 420",
                description: "You will serve the public.",
                tier: "major",
                opt1: "none",
                opt2: "none",
                pass1: "Go in chat or online and request 10 lewd tasks to perform. Take photos/videos while performing them and share them with the others.",
                pass2: "Do a 60minutes live stream and perform any sex acts others request in chat.",
                pass3: "Go outside and take a 30 minute walk wearing at least 5 items or clothes from other classes. Examples: fully dressed as a girl or in latex / wearing a tail, animal ears and a collar / wearing chastity cage, a buttplug and a small vibrator / wearing a rope harness, clothespins and cuffs / etc",
                tags: "exhibitionism"
            },
            7: {
                id: "7",
                imgUrl: "#",
                type: "major",
                name: "Sex Trades",
                name2: "anal, oral, double penetration",
                prerequisites: "415 ",
                description: "You will learn to use all of your holes to give and receive pleasure.",
                tier: "major",
                opt1: "none",
                opt2: "none",
                pass1: "Spitroast yourself for 30minutes with two dildos (sizes L and XL)",
                pass2: "Fuck yourself in the ass with a dildo (size XL) for 20minutes. Leave it in and then give another one (size L) a 15minutes blowjob with at least 50 deepthroats.",
                pass3: "Insert a dildo size XL in your ass and leave it in. Then deepthroat another one (size L) for 5 seconds - 15 times.",
                tags: "anal oral"
            },
            8: {
                id: "8",
                imgUrl: "#",
                type: "major",
                name: "Pet Science",
                name2: "pet-play",
                prerequisites: "417",
                days: "1 2 3 4 5 6 7",
                description: "Do you like pets? Well now you'll get to be one!",
                tier: "major",
                opt1: "none",
                opt2: "none",
                pass1: "For a period of 1440minutes - wear animal ears, a collar and a tail. Drink and eat from a bowl on the floor. Walk on all fours. Sleep in a cage. You may have four 30 minute rests.",
                pass2: "For a period of 240minutes - wear animal ears, a collar and a buttplug tail and tie yourself in a bitchsuit position.",
                pass3: "Spread your sex toys or other objects (20 minimum) around your apartment so that they could easily be reached by a toddler. Apply animal ears and a buttplug tail. Tie yourself in a bitchsuit position. Start collecting your toys one by one by bringing them to a common place with your mouth. You are done when all the toys have been gathered at one place. You have 180minutes.",
                tags: "pet"
            },
            9: {
                id: "9",
                imgUrl: "#",
                type: "major",
                name: "Fetish Design",
                name2: "fetish clothing",
                prerequisites: "418",
                description: "You will explore a variety of fetish clothing materials such as latex, leather, PVC and vinyl.",
                tier: "major",
                opt1: "none",
                opt2: "none",
                pass1: "Wear four pieces of fetish clothing or a catsuit for 1440minutes today.",
                pass2: "Wear a full catsuit (bodysuit) made of out latex/leather/pvc or vinyl for 720minutes today",
                pass3: "Wear a full catsuit (bodysuit) and a hood/mask made of out latex/leather/pvc or vinyl for 360minutes today.",
                tags: "fetish"
            },
            11: {
                id: "11",
                imgUrl: "#",
                type: "major",
                name: "Orgasm Science",
                name2: "forced orgasms, orgasm denial, post-orgasm torture",
                prerequisites: "409 413",
                description: "You will study the effects of prolonged sexual torment.",
                tier: "major",
                opt1: "none",
                opt2: "none",
                pass1: "Masturbate to the point of orgasm and continue all stimulation for 5 minutes after cumming.",
                pass2: "Masturbate to the point of orgasm and continue all stimulation until you cum again.",
                pass3: "For a period of 10080minutes edge 3 times a day but don't cum. Then on the last day cum 5 times.",
                tags: "orgasm"
            },
            12: {
                id: "12",
                imgUrl: "#",
                type: "major",
                name: "Oral Technologies",
                name2: "oral, cum-play",
                prerequisites: "405 406",
                description: "You will become proficient at pleasing cocks with your mouth and consuming large amounts of cum.",
                tier: "major",
                opt1: "none",
                opt2: "none",
                pass1: "Give a blowjob to a dildo (size L) for 45minutes and use cum (real or fake) as lube. Reapply it every 5 minutes.",
                pass2: "Deepthroat (23cm/~9inch) a dildo (size XL) 40 times in one sitting. After you're done deepthroat it another 10 times for 6 seconds each.",
                pass3: "Use a squirting dildo (size L). Give it blowjob for 15 minutes with at least 30 deepthroats (19cm/~7.5inch). On your last one, deepthroat it as far as you can and squirt 50ml of fake cum down your throat.",
                tags: "oral"
            },
            13: {
                id: "13",
                imgUrl: "#",
                type: "major",
                name: "Sex Slavery",
                name2: "bondage, masochism, submission",
                prerequisites: "414 420",
                description: "You will become a sex slave who derives pleasure from pain.",
                tier: "major",
                opt1: "none",
                opt2: "none",
                pass1: "Gag yourself. Make a clothespin zipper that runs from one of your breasts, around your navel and back to the other breast (20 clothespins minimum). Keep it on and spank your ass until it becomes red (50 times minimum). Then pull the zipper hard and fast.",
                pass2: "Attach clothespins to your nipples and insert a buttplug/vibrator/dildo in your ass. Tie yourself in a hogtie/frog-tie/mummy-tie for 60minutes while blindfolded and gagged.",
                pass3: "Go in chat or online and request 10 slave tasks to perform which preferably include bondage and pain. Spank your ass hard 20 times and your balls/pussy 10 times for every task you refuse.",
                tags: "slave"
            }
        }
    }

    generateData() {
        let cd = this.classesData();
        let classSet = [];
        let classPrereqSet = [];
        for(let tcn in cd){
            let tc = cd[tcn];
            let level = "error";
            switch (tc.id[0]) {
                case "1":
                    level = "one";
                    break;
                case "2":
                    level = "two";
                    break;
                case "3":
                    level = "three";
                    break;
                case "4":
                    level = "four";
                    break;
                case "5":
                    level = "five";
                    break;
            }
            classSet.push(aClass( (tc.id[1] + "" + tc.id[2]), level, tc.name, tc.name2));
            let prl = tc.prerequisites.split(" ");
            for(let pr of prl){
                if(pr){
                    classPrereqSet.push(edge( tc.id, pr));
                }
            }
        }

        let md = this.majorsData();
        let majorsSet = [];
        let majorsPrereqSet = [];
        for(let tmn in md){
            let tm = md[tmn];
            let level = "major";
            majorsSet.push(aClass( (tm.id), level, tm.name, tm.name2));
            let prl = tm.prerequisites.split(" ");
            for(let pr of prl){
                majorsPrereqSet.push(edge( tm.id, pr));
            }
        }

        return({classSet, classPrereqSet, majorsSet, majorsPrereqSet});
    }
}
